Sistema_Recomendador/Sistema_Recomendador/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('Usuarios.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
]

Sistema_Recomendador/Usuarios/urls.py
from django.urls import path
from Usuarios import views
# from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views

app_name = "Usuarios"

urlpatterns = [
    # path('lista_suscriptores', views.ListaSuscrptores.as_view(), name="lista_suscriptores"),
    path('registro', views.Registrar, name="registro"),
    path('inicio_sesion', auth_views.LoginView.as_view(template_name="home/inicio_sesion.html"), name="inicioS"),
    path('cerrar_sesion', auth_views.LogoutView.as_view(template_name="home/index.html"), name="cerrarS"),
    path('perfil', views.Profile.as_view(), name="profile"), 
]

Sistema_Recomendador/home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    # path('registro', views.Registrar.as_view(), name = "registro"),
    path('cerrar', views.Cerrar_sesion, name = "cerrar"),
    path('Mortal_kombat', views.detalle.as_view(), name = "detalle"),
    path('recomendaciones/', views.recomendaciones.as_view(), name="recomendaciones"),
    path('recomendaciones/?usuario=<int:id>', views.recomendaciones.as_view(), name="recomendaciones"),
    path('agregar/', views.agregar.as_view(), name="agregar"),
    path('peliculasdelusuario/', views.peliculasdelusuario.as_view(), name="peliculasdelusuario"),
    path('peliculasdelusuario/?usuario=<int:id>', views.peliculasdelusuario.as_view(), name="peliculasdelusuario")
]

Sistema_Recomendador/templates/base/head.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="shortcut icon" href="{% static 'images/icono.ico' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
{% block link%}{% endblock %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" type="text/css">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <!--nav bar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home:index'%}">
      <img src="{% static 'images/icono.png'%}" alt="logo" width="30" height="30" class="d-inline-block align-text-top">
      MoviesHub
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:index'%}">Inicio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:peliculasdelusuario'%}">Peliculas del usuario</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:recomendaciones'%}">Recomendaciones</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:agregar'%}">Agregar puntuación</a>
        </li>
        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="peliculasDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Peliculas
          </a>
          <ul class="dropdown-menu" aria-labelledby="peliculasDropdown">
            <li><a class="dropdown-item" href="#">Estrenos</a></li>
            <li><a class="dropdown-item" href="#">Ranking</a></li>
            <li><a class="dropdown-item" href="#">Mas vistas</a></li>
          </ul>
        </li> -->
      </ul>
      <!-- <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> -->
      {% if user.is_authenticated %}
      <ul class="navbar-nav me-2 mb-2 mb-lg-0">
      <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="usuarioDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color:white;">
        Bienvenido {{ user.username}}
      </a>
      <ul class="dropdown-menu" aria-labelledby="usuarioDropdown">
        <li><a class="dropdown-item" href="{% url 'Usuarios:profile' %}">Perfil</a></li>
        <li><a class="dropdown-item" href="#">Recomendados</a></li>
        <hr>
        <li><a class="dropdown-item" href="{% url 'Usuarios:cerrarS'%}">Cerrar sesión</a></li>
      </ul>
    </li>
  </ul>
      {% else %}
        <a href="{% url 'Usuarios:inicioS'%}"><button type="button" class="btn btn-primary" name="Inicio de sesión" style="margin: auto 15px;">Inicio de sesión</button></a>
        <a href="{% url 'Usuarios:registro'%}"><button type="button" class="btn btn-outline-primary" name="Registro">Registro</button></a>
        {% endif %}
    </div>
  </div>
</nav>
{%block style%}{%endblock%}
{%block content%}{%endblock%}
<footer>
  <p class="text-muted">© MoviesHub 2021. Todo los derechos reservados.</p>
</footer>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ" crossorigin="anonymous"></script>
</body>
</html>