Sistema_Recomendador/Sistema_Recomendador/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('Usuarios.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
]

Sistema_Recomendador/home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    # path('registro', views.Registrar.as_view(), name = "registro"),
    path('cerrar', views.Cerrar_sesion, name = "cerrar"),
    path('Mortal_kombat', views.detalle.as_view(), name = "detalle"),
    path('recomendaciones/', views.recomendaciones.as_view(), name="recomendaciones"),
    path('recomendaciones/?usuario=<int:id>', views.recomendaciones.as_view(), name="recomendaciones"),
    path('agregar/', views.agregar.as_view(), name="agregar"),
    path('peliculasdelusuario/', views.peliculasdelusuario.as_view(), name="peliculasdelusuario"),
    path('peliculasdelusuario/?usuario=<int:id>', views.peliculasdelusuario.as_view(), name="peliculasdelusuario")
]

Sistema_Recomendador/Usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

class Suscriptor(models.Model):
    nombre = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    nombreUser = models.CharField(max_length=50)
    correo = models.EmailField(max_length=200)
    contraseña = models.CharField(max_length=50)

    def __str__(self):
        return self.nombreUser

Sistema_Recomendador/home/models.py
from django.db import models

class Suscriptor(models.Model):
    name = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    username = models.CharField(unique=True, max_length=50)
    email = models.EmailField(max_length=200)
    password = models.CharField(max_length=50)

    def __str__(self):
        return self.username

Sistema_Recomendador/home/forms.py
from django import forms
from .models import Suscriptor

class SuscribirForm(forms.ModelForm):
    class Meta:
        model = Suscriptor
        fields = "__all__"
        labels = {
            'name': 'Nombre',
            'lastname': 'Apellidos',
            'username': 'Nombre de Usuario',
            'email': 'Correo',
            'password': 'Contraseña'
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'lastname': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellidos'}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Usuario'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'ejemplo@gmail.com'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Contraseña'}),
        }

Sistema_Recomendador/home/views.py
from django.shortcuts import render
from django.views import generic
from .models import Suscriptor
from .forms import SuscribirForm
from django.urls import reverse_lazy
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
import pandas as pd
from surprise import SVDpp
from surprise import Dataset, Reader
from surprise.model_selection import train_test_split
from surprise import accuracy
from collections import defaultdict
import pyodbc
import time,datetime

# Create your views here.

def Cerrar_sesion(request):
    logout(request)

class detalle(generic.TemplateView):
    template_name = "home/detalles.html"
    def get(self, request):
        context = {
            'title': "Mortal Kombat"
        }
        return render(request, "home/detalles.html", context)

class Index(generic.TemplateView):
    template_name = "home/index.html"
    def get(self, request):
        context = {
            'title': "MoviesHub"
        }
        return render(request, "home/index.html", context)


class agregar(generic.TemplateView):
    template_name = "home/agregar.html"

    def get(self, request):
        return render(request, "home/agregar.html")

    def post(self, request):
        heydict = dict(request.POST.lists())
        userId = heydict['userId'][0]
        movieId = heydict['movieId'][0]
        rating = heydict['rating'][0]

        print(userId, movieId,rating)
        #Database
        server = 'LOCALHOST\\SQLEXPRESS' 
        database = 'MoviesHub' 
        username = 'Gambino' 
        password = 'Colgate12'  
        cnxn = pyodbc.connect('DRIVER={SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)
        cursor = cnxn.cursor()

        query = "SELECT title, genres FROM movies_metadata WHERE movieId={0}".format(movieId)
        cursor.execute(query)
        rows = cursor.fetchall()
        
        title = rows[0][0]
        genres = rows[0][1]

        timestamp = time.mktime(datetime.datetime.today().timetuple())

        cursor.execute("INSERT INTO MoviesRatings (userId,movieId,rating,timestamp,title,genres) values (?,?,?,?,?,?)", userId, movieId, rating, timestamp, title, genres)
        cnxn.commit()
        cursor.close()

        mensaje = "Registro agregado correctamente"

        return render(request, "home/agregar.html", {'mensaje':mensaje})

class recomendaciones(generic.TemplateView):
    template_name = "home/recomendaciones.html"

    def get(self, request):
        return render(request, "home/recomendaciones.html")

    def post(self, request):
        heydict = dict(request.POST.lists())
        user = heydict['usuario'][0]
        #Database
        server = 'LOCALHOST\\SQLEXPRESS' 
        database = 'MoviesHub' 
        username = 'Gambino' 
        password = 'Colgate12'  
        cnxn = pyodbc.connect('DRIVER={SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)
        cursor = cnxn.cursor()
        
        queryMoviesRatings = "SELECT * FROM MoviesRatings WHERE movieId<250;"

        df_movies = pd.read_sql(queryMoviesRatings, cnxn)

        #Este dataframe tiene que tener siempre los ID de los usuarios, Id de peliculas y ratting dado por un usuario
        df_movies_to_model = df_movies[df_movies.columns[:-3]]

        queryRecommend = "SELECT title, genres FROM RecommendedMovies WHERE userId = {0};".format(user)
        df_recommend = pd.read_sql(queryRecommend, cnxn)
        queryErrores = "SELECT rmse FROM Errores WHERE userId = {0};".format(user)
        df_errores = pd.read_sql(queryErrores, cnxn)

        #Creamos una función que pasandole, un usuario, un DataFrame, un algoritmo y el número de recomendaciones que queremos
        def recommend_system(userId, dataframe, algorithm, n_commends):
            movie_ids = dataframe['movieId'].to_list()
            movies_watched = dataframe[dataframe["userId"] == userId]["movieId"]
            movies_no_watched = [movie for movie in movie_ids if movie not in movies_watched]

            preds = [algorithm.predict(uid=userId, iid=movie) for movie in movies_no_watched]
            commends_ratting = {pred[1]:pred[3] for pred in preds}
            order_dict = {k: v for k, v in sorted(commends_ratting.items(), key=lambda item: item[1])}

            top_predictions = list(order_dict.keys())[:n_commends]

            return dataframe[dataframe["movieId"].isin(top_predictions)][["title", "genres"]].drop_duplicates()

        if(len(df_recommend.index) == 0):
            #Usamos Reader() del paquete Surprise para poner los datos en el formato que nos piden los algoritmos
            reader = Reader()
            data = Dataset.load_from_df(df_movies_to_model, reader)

            #Separo en train y test
            train, test = train_test_split(data, test_size=0.25)

            #Instanciamos el algoritmo y entrenamos
            svd = SVDpp()
            svd.fit(train)
            preds = svd.test(test)

            #Métricas de evaluacin
            # mae = accuracy.mae(preds)
            rmse = accuracy.rmse(preds)
            rmse = rmse * 100
            rmse = format(rmse, '.2f')


            cursor.execute("INSERT INTO Errores (userId,rmse) values(?,?)", user, rmse)

            # Creamos todo el dataset completo con Train y Test
            trainfull = data.build_full_trainset()

            #Instanciamos de nuevo el algoritmo
            svd = SVDpp()
            #Entrenamos el algoritmo
            svd.fit(trainfull)


            #realizamos una prediccin para ver que todo funciona
            svd.predict(uid=1, iid=1)
            movies_recommended = recommend_system(user, df_movies, svd, 10)

            for index, row in movies_recommended.iterrows():
                cursor.execute("INSERT INTO RecommendedMovies (userId,movieId,title,genres) values(?,?,?,?)", user, index, row.title, row.genres)
            cnxn.commit()
            cursor.close()

            df_recommend = pd.read_sql(queryRecommend, cnxn)
            df_errores = pd.read_sql(queryErrores, cnxn)
        
        context = {
            'title': "Recomendaciones"
        }
        return render(request, "home/recomendacionesUser.html",{'df': df_recommend.values, 'user':user, 'dfErrores': df_errores.values}, context)

class peliculasdelusuario(generic.TemplateView):
    template_name = "home/peliculasdelusuario.html"
    def get(self, request):
        return render(request, "home/recomendaciones.html")
    def post(self, request):
        heydict = dict(request.POST.lists())
        user = heydict['usuario'][0]
        #Database
        server = 'LOCALHOST\\SQLEXPRESS' 
        database = 'MoviesHub' 
        username = 'Gambino' 
        password = 'Colgate12'  
        cnxn = pyodbc.connect('DRIVER={SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)
        cursor = cnxn.cursor()

        queryUserMovies = "SELECT title, genres, rating FROM MoviesRatings WHERE userId = {0};".format(user)
        dfUserMovies = pd.read_sql(queryUserMovies, cnxn)

        df = dfUserMovies.sort_values("rating", ascending=False)
        
        context = {
            'title': "Peliculas del usuario"
        }
        
        return render(request, "home/peliculasdelusuario.html",{'df': df.values, 'user':user}, context)

# class InicioS(generic.TemplateView):
#     template_name = "home/inicio_sesion.html"
#     def get(self, request):
#         context = {
#             'title': "Inicia de Sesión"
#         }
#         return render(request, "home/inicio_sesion.html", context)
#
# class InicioS(generic.TemplateView):
#     template_name = "home/inicio_sesion.html"
#     model = Suscriptor
#     def self(self, request):
#         if request.method == "POST":
#             form = AuthenticationForm(request, data=request.POST)
#         if form.is_valid():
#             usuario = form.cleaned_data.get('username')
#             contraseña = form.cleaned_data.get('password')
#             user = authenticate(username=usuario, password=contraseña)
#             if user is not None:
#                 login(request, user)
#                 success_url = reverse_lazy("home:index")
#
#         form = AuthenticationForm()
#         return render(request, "home/inicio_sesion.html", {'form': form})

# def InicioS(request):
#     model = Suscriptor
#     form_class = AuthenticationForm()
#     if request.method == "POST":
#         form = AuthenticationForm(request, data=request.POST)
#         if form.is_valid():
#             usuario = form.cleaned_data.get('username')
#             contraseña = form.cleaned_data.get('password')
#             queryset = Suscriptor.objects.filter(username=usuario, password=contraseña)
#             if queryset.exist:
#                 context = {
#                     'title': "Inicia de Sesión",
#                     'Usuario': usuario
#                 }
#             else:
#                 context = {
#                     'title': "Inicia de Sesión",
#                 }
#         else:
#             raise ValueError('Error en la entrada')
#     return render(request, "home/inicio_sesion.html", context)
#     success_url = reverse_lazy("home:index")

class InicioS(generic.FormView):
    template_name = "home/inicio_sesion.html"
    model = Suscriptor
    form_class = SuscribirForm
    def get(self, request):
        if request.method == "POST":
            form = AuthenticationForm(request, data=request.POST)
            if form.is_valid():
                usuario = form.cleaned_data.get('username')
                contraseña = form.cleaned_data.get('password')
                queryset = Suscriptor.objects.filter(username=usuario, password=contraseña)
                if queryset.exist:
                    context = {
                        'title': "Inicia de Sesión",
                        'Usuario': usuario
                    }
                else:

Sistema_Recomendador/templates/home/agregar.html
{% extends "base/head.html" %}
{% load static %}
{% block title%}Peliculas del usuario{% endblock %}
<link href="/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
<style>
       .bd-placeholder-img {
         font-size: 1.125rem;
         text-anchor: middle;
         -webkit-user-select: none;
         -moz-user-select: none;
         user-select: none;
       }

       @media (min-width: 768px) {
         .bd-placeholder-img-lg {
           font-size: 3.5rem;
         }
       }
</style>
  {%block link%}<link href="{% static 'css/signin.css' %}" rel="stylesheet">{%endblock%}
{% block content%}
<br>
<div class="container"> 
  {{mensaje}}
  <form action="" class="form-group col-sm-4" method="POST">
    {% csrf_token %}
    <label for="usuario">Numero de usuario: </label>
    <input type="number" class="form-control" id="userId" name="userId">
    <label for="usuario">Id de la pelicula: </label>
    <input type="number" class="form-control" id="movieId" name="movieId">
    <label for="usuario">Puntuacion: </label>
    <input type="number" class="form-control" id="rating" name="rating" max="5" min="0.5" step="0.5">
    <br>
    <button type="submit" class="btn btn-primary">Aceptar</button>
</form>
</div>
{% endblock %}

Sistema_Recomendador/templates/home/detalles.html
{% extends "base/head.html" %}
{% load static %}
{% block style %}
<style media="screen">
  .card {
    background-color: black;
    padding: 20px;
    border-radius: 10px;
  }
</style>
{% endblock %}
{% block title%}{{ title }}{% endblock %}
{% block content %}
<div class="container">
  <div class="movie">
    <div class="card mb-3">
    <div class="row g-0">
      <div class="col-md-4">
        <img class="moviePic" src="{% static 'images/Mortal_kombat.jpg' %}" alt="Mortal Kombat">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h3 class="card-title">{{ title }}</h3>
          <p class="card-text">
            Un boxeador fracasado descubre un secreto familiar que lo lleva a un torneo místico llamado Mortal Kombat en el
            que se encuentra con un grupo de guerreos que pelean a muerte para salvar a los reinos del malvado hechicero
            Shang Tsung.
          </p>
          <form class="" action="/">
            <h5>Votación</h5>
            <br>
            <label for="comentario">Comentarios:</label>
            <textarea name="comentario" rows="8" cols="80" placeholder="Dinos que opinas de la película: "></textarea>
            <button class="btn btn-primary" type="submit" name="enviar" style="display:block; margin-top:20px;">Enviar</button>
          </form>
        </div>
      </div>
    </div>
    </div>
    </div>
    <a href="/"><button class="brn btn-primary" type="button" name="regreso">Regresar</button></a>
</div>
{% endblock %}

Sistema_Recomendador/templates/home/index.html
{% extends "base/head.html" %}
{% load static %}
{%block title%}{{title}}{%endblock%}
{%block style%}
  <style media="screen">
  .card:hover {
    box-shadow: 5px 5px 40px aliceblue;
  }
  .d-block {
    filter: brightness(50%);
  }
  </style>
  {%endblock%}
  {%block content%}
    <section class="header">
      <!--Carrousel-->
      <div id="movieSlider" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#movieSlider" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#movieSlider" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#movieSlider" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'images/Mortal_kombat_slide.jpg' %}" class="d-block w-100" alt="Mortal Kombat">
        <div class="carousel-caption d-none d-md-block">
          <h5>Mortal Kombat</h5>
          <p>
            Un boxeador fracasado descubre un secreto familiar que lo lleva a un torneo místico llamado Mortal Kombat en el
            que se encuentra con un grupo de guerreos que pelean a muerte para salvar a los reinos del malvado hechicero
            Shang Tsung
          </p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/Godzilla_Kong_slide.jpg' %}" class="d-block w-100" alt="Godzilla vs Kong">
        <div class="carousel-caption d-none d-md-block">
          <h5>Godzilla vs Kong</h5>
          <p>
            Godzilla y Kong, las dos fuerzas más poderosas del planeta se enfrentan en combate impresionante que sacude
            los cimientos de la humanidad
          </p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/justice_leage_slide.jpg'%}" class="d-block w-100" alt="Justice Leage">
        <div class="carousel-caption d-none d-md-block">
          <h5>La liga de la justicia de Snyder</h5>
          <p>
            Decidido a que el último sacrificio de SuperMan no sea en vano, Bruce Wayne une fuerza con Diana Prince para
            reunir un nuevo equipo de metahumanos para proteger al mundo de una amenaza inminente
          </p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#movieSlider" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#movieSlider" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
    </section>

    <!-- Content -->
<div class="container-fluid">
  <!-- Movies Section -->
  <section class="movies inline">
    <h1>Películas</h1>
    <div class="row row-cols-1 row-cols-md-3 g-4">
  <div class="col">
    <a href="/Mortal_kombat">
      <div class="card">
        <img src="{% static 'images/Mortal_kombat.jpg' %}" class="card-img-top" alt="Mortal Kombat">
        <div class="card-body">
          <h5 class="card-title">Mortal Kombat</h5>
          <button type="button" class="btn btn-primary" name="button">Ver</button>
        </div>
      </div>
    </a>
  </div>
  <div class="col">
    <div class="card">
      <img src="{% static 'images/Godzilla_Kong.jpg' %}" class="card-img-top" alt="Godzilla vs Kong">
      <div class="card-body">
        <h5 class="card-title">Godzilla vs Kong</h5>
        <button type="button" class="btn btn-primary" name="button">Ver</button>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="{% static 'images/Justice_leage.jpg' %}" class="card-img-top" alt="Liga de la justicia">
      <div class="card-body">
        <h5 class="card-title">La liga de la Justicia de Zack Snyder</h5>
        <button type="button" class="btn btn-primary" name="button">Ver</button>
      </div>
  </div>
  </div>
  <div class="col">
  <div class="card">
    <img src="{% static 'images/Raya.jpg' %}" class="card-img-top" alt="Raya y el último dragón">
    <div class="card-body">
      <h5 class="card-title">Raya y el último dragón</h5>
      <button type="button" class="btn btn-primary" name="button">Ver</button>
    </div>
  </div>
  </div>
  <div class="col">
  <div class="card">
    <img src="{% static 'images/To_all_the_boys.jpg' %}" class="card-img-top" alt="A todos los chicos de los que me enamoré">
    <div class="card-body">
      <h5 class="card-title">A todos los chicos de los que me enamoré</h5>
      <button type="button" class="btn btn-primary" name="button">Ver</button>
    </div>
  </div>
  </div>
  <div class="col">
  <div class="card">
    <img src="{% static 'images/Sacrificio.jpg'%}" class="card-img-top" alt="Sacrificio">
    <div class="card-body">
      <h5 class="card-title">Sacrificio</h5>
      <button type="button" class="btn btn-primary" name="button">Ver</button>
    </div>
  </div>
  </div>
  <div class="col">
  <div class="card">
    <img src="{% static 'images/Queens.jpg' %}" class="card-img-top" alt="Érase una vez en Queens">
    <div class="card-body">
      <h5 class="card-title">Érase una vez en Queens</h5>
      <button type="button" class="btn btn-primary" name="button">Ver</button>
    </div>
  </div>
  </div>
  <div class="col">
  <div class="card">
    <img src="{% static 'images/Maya.jpg' %}" class="card-img-top" alt="Maya y el orbe dorado">
    <div class="card-body">
      <h5 class="card-title">Maya y el orbe dorado</h5>
      <button type="button" class="btn btn-primary" name="button">Ver</button>
    </div>
  </div>
  </div>
  <div class="col">
  <div class="card">
    <img src="{% static 'images/El_despertar.jpg' %}" class="card-img-top" alt="Maggie Simpson: El despertar de la siesta">
    <div class="card-body">
      <h5 class="card-title">Maggie Simpson: El despertar de la siesta</h5>
      <button type="button" class="btn btn-primary" name="button">Ver</button>
    </div>
  </div>
  </div>
  </section>
  <!-- Ranking section -->
  <section class="ranked_Movies inline">
    <h2>👑Ranking👑</h2>
    <hr>
    <h3>1.</h3>
    <div class="card">
      <img src="{% static 'images/vengadores_fin.jpg' %}" class="card-img-top" alt="Vengadores: Fin del juego">
      <div class="card-body">
        <h5 class="card-title">Vengadores: Fin del Juego</h5>
        <button type="button" class="btn btn-primary" name="button">Ver</button>
      </div>
    </div>
  </section>
  </div>
</div>
{%endblock%}

Sistema_Recomendador/templates/home/registro.html
{% extends "base/head.html" %}
{% load static %}
{% block title%}Registro{% endblock %}
{% block content %}

<div class="container" style="text-align:center;">
    <section id="registro" class="inline">
      <div class="py-5 text-center">
        <img class="d-block mx-auto mb-4" src="{% static 'images/MoviesHub.png' %}" alt="logo" style="filter: brightness(100%); border-radius:10%;">
        <h2>Registro</h2>
        <p class="lead">Registrate para poder comentar, calificar películas y ser parte de nuestra comunidad!</p>
      </div>
      <div class="row g-5">
        <!-- Come here i you need to reduce the size of the form -->
        <div class="col-md-7 col-lg-12">
          <form class="needs-validation form_signin" method="POST" enctype="multipart/form-data" style="text-align:initial" novalidate>
            {% csrf_token %}
            <!-- {{ form.as_p }} -->
            <div class="row" style="padding-top:30px;">
              <div class="col-6">
                <label for="id_nombre" class="form-label">Nombre:</label>
                {{ form.first_name }}
                {{ form.help_text }}
              </div>
              <div class="col-6">
                <label for="id_nombre" class="form-label">Apellidos:</label>
                {{ form.last_name }}
                {{ form.help_text }}
              </div>
            </div>
            <div class="row" style="padding-top:30px;">
              <div class="col-6">
                <label for="id_nombre" class="form-label">Nombre de Usuarios:</label>
                {{ form.username }}
                {{ form.help_text }}
              </div>
              <div class="col-6">
                <label for="id_nombre" class="form-label">Correo:</label>
                {{ form.email }}
                {{ form.help_text }}
              </div>
            </div>
            <div class="row" style="padding-top:30px;">
              <div class="col-6">
                <label for="id_nombre" class="form-label">Contraseña:</label>
                {{ form.password }}
                {{ form.help_text }}
              </div>
              <div class="col-6">
                <label for="id_nombre" class="form-label">Confirme Contraseña:</label>
                {{ form.password }}
                {{ form.help_text }}
              </div>
            </div>
            <hr class="my-4">
            <div class="buttoms" style="text-align:center;">
              <button class="btn btn-primary btn-lg" style="margin:auto;width:25%;" type="submit">Registrar</button>
              <button class="btn btn-primary btn-lg" style="margin:auto;width:25%;" type="reset">Cancelar</button>
            </div>
          </form>
        </div>
        </div>
    </section>
    </div>
{% endblock %}

Sistema_Recomendador/templates/home/registro2.html
{% extends "base/head.html" %}
{% load static %}
{% block title%}{{title}}{% endblock %}
{% block content %}

<div class="container">
    <section id="registro" class="inline">
      <div class="py-5 text-center">
        <img class="d-block mx-auto mb-4" src="{% static 'images/MoviesHub.png' %}" alt="logo" style="filter: brightness(100%); border-radius:10%;">
        <h2>Registro</h2>
        <p class="lead">Registrate para poder comentar, calificar películas y ser parte de nuestra comunidad!</p>
      </div>
      <div class="row g-5">
        <!-- Come here i you need to reduce the size of the form -->
        <div class="col-md-7 col-lg-12">
          <form class="needs-validation" method="POST" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            {{ form.as_p }}

            <hr class="my-4">
            <button class="btn btn-primary btn-lg" style="margin:auto;width:25%;" type="submit">Registrar</button>
            <button class="btn btn-primary btn-lg" style="margin:auto;width:25%;" type="reset">Cancelar</button>
            <div class="row g-3">
              <div class="col-sm-6">
                <label for="nombre" class="form-label">Nombre</label>
                <input type="text" class="form-control" name="nombre" placeholder="Nombre" required>
                <div class="invalid-feedback">
                  Nombre invalido
                </div>
              </div>

              <div class="col-sm-6">
                <label for="id_apellidos" class="form-label">Apellido</label>
                <input type="text" class="form-control" placeholder="Apellido" name="apellido" required>
                <div class="invalid-feedback">
                  Apellido invalido
                </div>
              </div>

              <div class="col-6">
                <label for="nombreUser" class="form-label">Nombre de usuario</label>
                <div class="input-group has-validation">
                  <span class="input-group-text">@</span>
                  <input type="text" class="form-control" placeholder="Nombre de Usuario" required>
                <div class="invalid-feedback">
                    Nombre de usuario valido requerido
                  </div>
                </div>
              </div>

              <div class="col-6">
                <label for="id_correo" class="form-label">Correo</label>
                <input type="email" class="form-control" id="correo" placeholder="you@example.com" required>
                <div class="invalid-feedback">
                  Correo invalido
                </div>
              </div>

              <div class="col-6">
                <label for="contraseña" class="form-label">Contraseña</label>
                <div class="input-group has-validation">
                  <input type="password" class="form-control" id="contraseña" required>
                <div class="invalid-feedback">
                    Contraseña requiere mínimo 8 caracteres, una mayúscula y un número
                  </div>
                </div>
              </div>

              <div class="col-6">
                <label for="confirmCon" class="form-label">Confirme Contraseña</label>
                <input type="password" class="form-control" id="confirmCon" required>
                <div class="invalid-feedback">
                  Contraseña no concuerda
                </div>
              </div>

            <hr class="my-4">
            <button class="btn btn-primary btn-lg" style="margin:auto;width:25%;" type="submit">Registrar</button>
            <button class="btn btn-primary btn-lg" style="margin:auto;width:25%;" type="reset">Cancelar</button>
          </form>
        </div>
    </section>
    </div>
{% endblock %}